import 'package:flutter/material.dart';

class AppMaterialTheme {
  static ThemeData getThemeDataFromColorScheme({
    ColorScheme? colorScheme,
    required Brightness brightness,
  }) {
    return ThemeData(
      colorScheme:
          colorScheme ??
          ((brightness == Brightness.light)
              ? lightFallbackTheme
              : darkFallbackTheme),
    );
  }

  static ColorScheme lightFallbackTheme = const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff1d275c),
    surfaceTint: Color(0xff515b92),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xff3b457b),
    onPrimaryContainer: Color(0xffffffff),
    secondary: Color(0xff282b3d),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xff45485c),
    onSecondaryContainer: Color(0xffffffff),
    tertiary: Color(0xff3f2239),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xff5f3f57),
    onTertiaryContainer: Color(0xffffffff),
    error: Color(0xff600004),
    onError: Color(0xffffffff),
    errorContainer: Color(0xff98000a),
    onErrorContainer: Color(0xffffffff),
    surface: Color(0xfffbf8ff),
    onSurface: Color(0xff000000),
    onSurfaceVariant: Color(0xff000000),
    outline: Color(0xff2b2c34),
    outlineVariant: Color(0xff484851),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff303036),
    inversePrimary: Color(0xffbac3ff),
    primaryFixed: Color(0xff3b457b),
    onPrimaryFixed: Color(0xffffffff),
    primaryFixedDim: Color(0xff242e63),
    onPrimaryFixedVariant: Color(0xffffffff),
    secondaryFixed: Color(0xff45485c),
    onSecondaryFixed: Color(0xffffffff),
    secondaryFixedDim: Color(0xff2f3244),
    onSecondaryFixedVariant: Color(0xffffffff),
    tertiaryFixed: Color(0xff5f3f57),
    onTertiaryFixed: Color(0xffffffff),
    tertiaryFixedDim: Color(0xff472940),
    onTertiaryFixedVariant: Color(0xffffffff),
    surfaceDim: Color(0xffb9b8bf),
    surfaceBright: Color(0xfffbf8ff),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff2f0f7),
    surfaceContainer: Color(0xffe3e1e9),
    surfaceContainerHigh: Color(0xffd5d3db),
    surfaceContainerHighest: Color(0xffc7c5cd),
  );

  static ColorScheme darkFallbackTheme = const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xffefeeff),
    surfaceTint: Color(0xffbac3ff),
    onPrimary: Color(0xff000000),
    primaryContainer: Color(0xffb5bffd),
    onPrimaryContainer: Color(0xff000531),
    secondary: Color(0xffefeeff),
    onSecondary: Color(0xff000000),
    secondaryContainer: Color(0xffbfc1d9),
    onSecondaryContainer: Color(0xff070a1b),
    tertiary: Color(0xffffeaf6),
    onTertiary: Color(0xff000000),
    tertiaryContainer: Color(0xffe1b6d4),
    onTertiaryContainer: Color(0xff1a0317),
    error: Color(0xffffece9),
    onError: Color(0xff000000),
    errorContainer: Color(0xffffaea4),
    onErrorContainer: Color(0xff220001),
    surface: Color(0xff121318),
    onSurface: Color(0xffffffff),
    onSurfaceVariant: Color(0xffffffff),
    outline: Color(0xfff0effa),
    outlineVariant: Color(0xffc2c1cc),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffe3e1e9),
    inversePrimary: Color(0xff3a447a),
    primaryFixed: Color(0xffdee0ff),
    onPrimaryFixed: Color(0xff000000),
    primaryFixedDim: Color(0xffbac3ff),
    onPrimaryFixedVariant: Color(0xff000940),
    secondaryFixed: Color(0xffdfe1f9),
    onSecondaryFixed: Color(0xff000000),
    secondaryFixedDim: Color(0xffc3c5dd),
    onSecondaryFixedVariant: Color(0xff0d1021),
    tertiaryFixed: Color(0xffffd7f2),
    onTertiaryFixed: Color(0xff000000),
    tertiaryFixedDim: Color(0xffe5bad8),
    onTertiaryFixedVariant: Color(0xff21071d),
    surfaceDim: Color(0xff121318),
    surfaceBright: Color(0xff504f56),
    surfaceContainerLowest: Color(0xff000000),
    surfaceContainerLow: Color(0xff1f1f25),
    surfaceContainer: Color(0xff303036),
    surfaceContainerHigh: Color(0xff3b3b41),
    surfaceContainerHighest: Color(0xff46464c),
  );
}
